/* ============================================
   NUIT NOIRE TATTOO - countries.js
   Liste ISO 3166-1 des pays, noms FR / EN.
   Fichier genere, ne pas editer a la main.
   Utilise par la page panier pour construire le menu deroulant
   des pays de livraison a partir des zones de data/shipping.json.
   ============================================ */

window.NNCountries = {
  AF: { fr: "Afghanistan", en: "Afghanistan" },
  ZA: { fr: "Afrique du Sud", en: "South Africa" },
  AL: { fr: "Albanie", en: "Albania" },
  DZ: { fr: "Algérie", en: "Algeria" },
  DE: { fr: "Allemagne", en: "Germany" },
  AD: { fr: "Andorre", en: "Andorra" },
  AO: { fr: "Angola", en: "Angola" },
  AI: { fr: "Anguilla", en: "Anguilla" },
  AQ: { fr: "Antarctique", en: "Antarctica" },
  AG: { fr: "Antigua-et-Barbuda", en: "Antigua & Barbuda" },
  SA: { fr: "Arabie saoudite", en: "Saudi Arabia" },
  AR: { fr: "Argentine", en: "Argentina" },
  AM: { fr: "Arménie", en: "Armenia" },
  AW: { fr: "Aruba", en: "Aruba" },
  AU: { fr: "Australie", en: "Australia" },
  AT: { fr: "Autriche", en: "Austria" },
  AZ: { fr: "Azerbaïdjan", en: "Azerbaijan" },
  BS: { fr: "Bahamas", en: "Bahamas" },
  BH: { fr: "Bahreïn", en: "Bahrain" },
  BD: { fr: "Bangladesh", en: "Bangladesh" },
  BB: { fr: "Barbade", en: "Barbados" },
  BE: { fr: "Belgique", en: "Belgium" },
  BZ: { fr: "Belize", en: "Belize" },
  BJ: { fr: "Bénin", en: "Benin" },
  BM: { fr: "Bermudes", en: "Bermuda" },
  BT: { fr: "Bhoutan", en: "Bhutan" },
  BY: { fr: "Biélorussie", en: "Belarus" },
  BO: { fr: "Bolivie", en: "Bolivia" },
  BA: { fr: "Bosnie-Herzégovine", en: "Bosnia & Herzegovina" },
  BW: { fr: "Botswana", en: "Botswana" },
  BR: { fr: "Brésil", en: "Brazil" },
  BN: { fr: "Brunei", en: "Brunei" },
  BG: { fr: "Bulgarie", en: "Bulgaria" },
  BF: { fr: "Burkina Faso", en: "Burkina Faso" },
  BI: { fr: "Burundi", en: "Burundi" },
  KH: { fr: "Cambodge", en: "Cambodia" },
  CM: { fr: "Cameroun", en: "Cameroon" },
  CA: { fr: "Canada", en: "Canada" },
  CV: { fr: "Cap-Vert", en: "Cape Verde" },
  CL: { fr: "Chili", en: "Chile" },
  CN: { fr: "Chine", en: "China" },
  CY: { fr: "Chypre", en: "Cyprus" },
  CO: { fr: "Colombie", en: "Colombia" },
  KM: { fr: "Comores", en: "Comoros" },
  CG: { fr: "Congo-Brazzaville", en: "Congo - Brazzaville" },
  CD: { fr: "Congo-Kinshasa", en: "Congo - Kinshasa" },
  KR: { fr: "Corée du Sud", en: "South Korea" },
  CR: { fr: "Costa Rica", en: "Costa Rica" },
  CI: { fr: "Côte d’Ivoire", en: "Côte d’Ivoire" },
  HR: { fr: "Croatie", en: "Croatia" },
  CW: { fr: "Curaçao", en: "Curaçao" },
  DK: { fr: "Danemark", en: "Denmark" },
  DJ: { fr: "Djibouti", en: "Djibouti" },
  DM: { fr: "Dominique", en: "Dominica" },
  EG: { fr: "Égypte", en: "Egypt" },
  AE: { fr: "Émirats arabes unis", en: "United Arab Emirates" },
  EC: { fr: "Équateur", en: "Ecuador" },
  ER: { fr: "Érythrée", en: "Eritrea" },
  ES: { fr: "Espagne", en: "Spain" },
  EE: { fr: "Estonie", en: "Estonia" },
  SZ: { fr: "Eswatini", en: "Eswatini" },
  VA: { fr: "État de la Cité du Vatican", en: "Vatican City" },
  US: { fr: "États-Unis", en: "United States" },
  ET: { fr: "Éthiopie", en: "Ethiopia" },
  FJ: { fr: "Fidji", en: "Fiji" },
  FI: { fr: "Finlande", en: "Finland" },
  FR: { fr: "France", en: "France" },
  GA: { fr: "Gabon", en: "Gabon" },
  GM: { fr: "Gambie", en: "Gambia" },
  GE: { fr: "Géorgie", en: "Georgia" },
  GS: { fr: "Géorgie du Sud-et-les Îles Sandwich du Sud", en: "South Georgia & South Sandwich Islands" },
  GH: { fr: "Ghana", en: "Ghana" },
  GI: { fr: "Gibraltar", en: "Gibraltar" },
  GR: { fr: "Grèce", en: "Greece" },
  GD: { fr: "Grenade", en: "Grenada" },
  GL: { fr: "Groenland", en: "Greenland" },
  GP: { fr: "Guadeloupe", en: "Guadeloupe" },
  GU: { fr: "Guam", en: "Guam" },
  GT: { fr: "Guatemala", en: "Guatemala" },
  GG: { fr: "Guernesey", en: "Guernsey" },
  GN: { fr: "Guinée", en: "Guinea" },
  GQ: { fr: "Guinée équatoriale", en: "Equatorial Guinea" },
  GW: { fr: "Guinée-Bissau", en: "Guinea-Bissau" },
  GY: { fr: "Guyana", en: "Guyana" },
  GF: { fr: "Guyane française", en: "French Guiana" },
  HT: { fr: "Haïti", en: "Haiti" },
  HN: { fr: "Honduras", en: "Honduras" },
  HU: { fr: "Hongrie", en: "Hungary" },
  BV: { fr: "Île Bouvet", en: "Bouvet Island" },
  AC: { fr: "Île de l’Ascension", en: "Ascension Island" },
  IM: { fr: "Île de Man", en: "Isle of Man" },
  AX: { fr: "Îles Åland", en: "Åland Islands" },
  KY: { fr: "Îles Caïmans", en: "Cayman Islands" },
  CK: { fr: "Îles Cook", en: "Cook Islands" },
  FO: { fr: "Îles Féroé", en: "Faroe Islands" },
  FK: { fr: "Îles Malouines", en: "Falkland Islands" },
  PN: { fr: "Îles Pitcairn", en: "Pitcairn Islands" },
  SB: { fr: "Îles Salomon", en: "Solomon Islands" },
  TC: { fr: "Îles Turques-et-Caïques", en: "Turks & Caicos Islands" },
  VG: { fr: "Îles Vierges britanniques", en: "British Virgin Islands" },
  IN: { fr: "Inde", en: "India" },
  ID: { fr: "Indonésie", en: "Indonesia" },
  IQ: { fr: "Irak", en: "Iraq" },
  IE: { fr: "Irlande", en: "Ireland" },
  IS: { fr: "Islande", en: "Iceland" },
  IL: { fr: "Israël", en: "Israel" },
  IT: { fr: "Italie", en: "Italy" },
  JM: { fr: "Jamaïque", en: "Jamaica" },
  JP: { fr: "Japon", en: "Japan" },
  JE: { fr: "Jersey", en: "Jersey" },
  JO: { fr: "Jordanie", en: "Jordan" },
  KZ: { fr: "Kazakhstan", en: "Kazakhstan" },
  KE: { fr: "Kenya", en: "Kenya" },
  KG: { fr: "Kirghizstan", en: "Kyrgyzstan" },
  KI: { fr: "Kiribati", en: "Kiribati" },
  XK: { fr: "Kosovo", en: "Kosovo" },
  KW: { fr: "Koweït", en: "Kuwait" },
  RE: { fr: "La Réunion", en: "Réunion" },
  LA: { fr: "Laos", en: "Laos" },
  LS: { fr: "Lesotho", en: "Lesotho" },
  LV: { fr: "Lettonie", en: "Latvia" },
  LB: { fr: "Liban", en: "Lebanon" },
  LR: { fr: "Liberia", en: "Liberia" },
  LY: { fr: "Libye", en: "Libya" },
  LI: { fr: "Liechtenstein", en: "Liechtenstein" },
  LT: { fr: "Lituanie", en: "Lithuania" },
  LU: { fr: "Luxembourg", en: "Luxembourg" },
  MK: { fr: "Macédoine du Nord", en: "North Macedonia" },
  MG: { fr: "Madagascar", en: "Madagascar" },
  MY: { fr: "Malaisie", en: "Malaysia" },
  MW: { fr: "Malawi", en: "Malawi" },
  MV: { fr: "Maldives", en: "Maldives" },
  ML: { fr: "Mali", en: "Mali" },
  MT: { fr: "Malte", en: "Malta" },
  MA: { fr: "Maroc", en: "Morocco" },
  MQ: { fr: "Martinique", en: "Martinique" },
  MU: { fr: "Maurice", en: "Mauritius" },
  MR: { fr: "Mauritanie", en: "Mauritania" },
  YT: { fr: "Mayotte", en: "Mayotte" },
  MX: { fr: "Mexique", en: "Mexico" },
  MD: { fr: "Moldavie", en: "Moldova" },
  MC: { fr: "Monaco", en: "Monaco" },
  MN: { fr: "Mongolie", en: "Mongolia" },
  ME: { fr: "Monténégro", en: "Montenegro" },
  MS: { fr: "Montserrat", en: "Montserrat" },
  MZ: { fr: "Mozambique", en: "Mozambique" },
  MM: { fr: "Myanmar (Birmanie)", en: "Myanmar (Burma)" },
  NA: { fr: "Namibie", en: "Namibia" },
  NR: { fr: "Nauru", en: "Nauru" },
  NP: { fr: "Népal", en: "Nepal" },
  NI: { fr: "Nicaragua", en: "Nicaragua" },
  NE: { fr: "Niger", en: "Niger" },
  NG: { fr: "Nigeria", en: "Nigeria" },
  NU: { fr: "Niue", en: "Niue" },
  NO: { fr: "Norvège", en: "Norway" },
  NC: { fr: "Nouvelle-Calédonie", en: "New Caledonia" },
  NZ: { fr: "Nouvelle-Zélande", en: "New Zealand" },
  OM: { fr: "Oman", en: "Oman" },
  UG: { fr: "Ouganda", en: "Uganda" },
  UZ: { fr: "Ouzbékistan", en: "Uzbekistan" },
  PK: { fr: "Pakistan", en: "Pakistan" },
  PA: { fr: "Panama", en: "Panama" },
  PG: { fr: "Papouasie-Nouvelle-Guinée", en: "Papua New Guinea" },
  PY: { fr: "Paraguay", en: "Paraguay" },
  NL: { fr: "Pays-Bas", en: "Netherlands" },
  BQ: { fr: "Pays-Bas caribéens", en: "Caribbean Netherlands" },
  PE: { fr: "Pérou", en: "Peru" },
  PH: { fr: "Philippines", en: "Philippines" },
  PL: { fr: "Pologne", en: "Poland" },
  PF: { fr: "Polynésie française", en: "French Polynesia" },
  PR: { fr: "Porto Rico", en: "Puerto Rico" },
  PT: { fr: "Portugal", en: "Portugal" },
  QA: { fr: "Qatar", en: "Qatar" },
  HK: { fr: "R.A.S. chinoise de Hong Kong", en: "Hong Kong SAR China" },
  MO: { fr: "R.A.S. chinoise de Macao", en: "Macao SAR China" },
  CF: { fr: "République centrafricaine", en: "Central African Republic" },
  DO: { fr: "République dominicaine", en: "Dominican Republic" },
  RO: { fr: "Roumanie", en: "Romania" },
  GB: { fr: "Royaume-Uni", en: "United Kingdom" },
  RU: { fr: "Russie", en: "Russia" },
  RW: { fr: "Rwanda", en: "Rwanda" },
  EH: { fr: "Sahara occidental", en: "Western Sahara" },
  BL: { fr: "Saint-Barthélemy", en: "St. Barthélemy" },
  KN: { fr: "Saint-Christophe-et-Niévès", en: "St. Kitts & Nevis" },
  SM: { fr: "Saint-Marin", en: "San Marino" },
  MF: { fr: "Saint-Martin", en: "St. Martin" },
  SX: { fr: "Saint-Martin (partie néerlandaise)", en: "Sint Maarten" },
  PM: { fr: "Saint-Pierre-et-Miquelon", en: "St. Pierre & Miquelon" },
  VC: { fr: "Saint-Vincent-et-les Grenadines", en: "St. Vincent & Grenadines" },
  SH: { fr: "Sainte-Hélène", en: "St. Helena" },
  LC: { fr: "Sainte-Lucie", en: "St. Lucia" },
  SV: { fr: "Salvador", en: "El Salvador" },
  WS: { fr: "Samoa", en: "Samoa" },
  ST: { fr: "Sao Tomé-et-Principe", en: "São Tomé & Príncipe" },
  SN: { fr: "Sénégal", en: "Senegal" },
  RS: { fr: "Serbie", en: "Serbia" },
  SC: { fr: "Seychelles", en: "Seychelles" },
  SL: { fr: "Sierra Leone", en: "Sierra Leone" },
  SG: { fr: "Singapour", en: "Singapore" },
  SK: { fr: "Slovaquie", en: "Slovakia" },
  SI: { fr: "Slovénie", en: "Slovenia" },
  SO: { fr: "Somalie", en: "Somalia" },
  SS: { fr: "Soudan du Sud", en: "South Sudan" },
  LK: { fr: "Sri Lanka", en: "Sri Lanka" },
  SE: { fr: "Suède", en: "Sweden" },
  CH: { fr: "Suisse", en: "Switzerland" },
  SR: { fr: "Suriname", en: "Suriname" },
  SJ: { fr: "Svalbard et Jan Mayen", en: "Svalbard & Jan Mayen" },
  TJ: { fr: "Tadjikistan", en: "Tajikistan" },
  TW: { fr: "Taïwan", en: "Taiwan" },
  TZ: { fr: "Tanzanie", en: "Tanzania" },
  TD: { fr: "Tchad", en: "Chad" },
  CZ: { fr: "Tchéquie", en: "Czechia" },
  TF: { fr: "Terres australes françaises", en: "French Southern Territories" },
  IO: { fr: "Territoire britannique de l’océan Indien", en: "British Indian Ocean Territory" },
  PS: { fr: "Territoires palestiniens", en: "Palestinian Territories" },
  TH: { fr: "Thaïlande", en: "Thailand" },
  TL: { fr: "Timor oriental", en: "Timor-Leste" },
  TG: { fr: "Togo", en: "Togo" },
  TK: { fr: "Tokelau", en: "Tokelau" },
  TO: { fr: "Tonga", en: "Tonga" },
  TT: { fr: "Trinité-et-Tobago", en: "Trinidad & Tobago" },
  TA: { fr: "Tristan da Cunha", en: "Tristan da Cunha" },
  TN: { fr: "Tunisie", en: "Tunisia" },
  TM: { fr: "Turkménistan", en: "Turkmenistan" },
  TR: { fr: "Turquie", en: "Türkiye" },
  TV: { fr: "Tuvalu", en: "Tuvalu" },
  UA: { fr: "Ukraine", en: "Ukraine" },
  UY: { fr: "Uruguay", en: "Uruguay" },
  VU: { fr: "Vanuatu", en: "Vanuatu" },
  VE: { fr: "Venezuela", en: "Venezuela" },
  VN: { fr: "Viêt Nam", en: "Vietnam" },
  WF: { fr: "Wallis-et-Futuna", en: "Wallis & Futuna" },
  YE: { fr: "Yémen", en: "Yemen" },
  ZM: { fr: "Zambie", en: "Zambia" },
  ZW: { fr: "Zimbabwe", en: "Zimbabwe" }
};
